name: l_token
description: A Flutter project of Wallet.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # todo remove
  flutter_redux: ^0.5.3
  # state management
  flutter_bloc: ^0.5.2
  # QR code
  qr_flutter: ^1.1.5
  # font icon
  font_awesome_flutter: ^8.2.0
  # token core
  token_core_plugin: ^0.0.2
  # network framework
  dio: ^1.0.13
  # event bus
  event_bus: ^1.0.1
  # log
  logging: ^0.11.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:

    # images
    - assets/images/ic_logo.png
    - assets/images/ic_default_user_avatar.png
    - assets/images/ic_default_wallet_avatar_0.png
    - assets/images/ic_default_wallet_avatar_1.png
    - assets/images/ic_default_wallet_avatar_2.png
    - assets/images/ic_default_wallet_avatar_3.png
    - assets/images/ic_default_wallet_avatar_4.png
    - assets/images/ic_default_wallet_avatar_5.png
    - assets/images/ic_default_wallet_avatar_6.png
    - assets/images/ic_default_wallet_avatar_7.png
    - assets/images/ic_default_wallet_avatar_8.png
    - assets/images/ic_default_wallet_avatar_9.png
    - assets/images/ic_default_wallet_avatar_10.png
    - assets/images/ic_gas_price_fast.png
    - assets/images/ic_gas_price_slow.png
    - assets/images/ic_qrcode_scan.png
    - assets/images/ic_qrcode.png
    - assets/images/ic_transfer_arp_b.png
    - assets/images/ic_transfer_bat_b.png
    - assets/images/ic_transfer_bnt_b.png
    - assets/images/ic_transfer_eos_b.png
    - assets/images/ic_transfer_eth_b.png
    - assets/images/ic_transfer_every_b.png
    - assets/images/ic_transfer_iost_b.png
    - assets/images/ic_transfer_knc_b.png
    - assets/images/ic_transfer_lrc_b.png
    - assets/images/ic_transfer_rdn_b.png
    - assets/images/ic_transfer_req_b.png
    - assets/images/ic_transfer_rhoc_b.png
    - assets/images/ic_transfer_vite_b.png
    - assets/images/ic_transfer_weth_b.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
